<nav>
	<ul>
		<li class='active'><a href='index.php'><span>Home</span></a></li>
		<li class='has-sub'><a href='#'><span>Acesso</span></a>
			<ul>
				<li><a href='login.php'><span>Login</span></a></li>
				<li class='last'><a href='registarU.php'><span>Registar</span></a></li>
			</ul>
		</li>
		<li class='has-sub'><a href='#'><span>Procurar</span></a>
			<ul>
				<li><a href='procurarL.php'><span>Livros</span></a></li>
				<li class='last'><a href='procurarA.php'><span>Autores</span></a></li>
			</ul>
		</li>
	</ul>
</nav>