<nav>
	<ul>
		<li class='active'><a href='pag_admin.php'><span>Home</span></a></li>
		<li class='has-sub'><a href='#'><span>Acesso</span></a>
			<ul>
				<li><a href='alterar_nivel.php'><span>Alterar Nível utilizador</span></a></li>
				<!--<li><a href='desativar_utilizador.php'><span>Desativar utilizador</span></a></li>
				<li><a href='validar_utilizador.php'><span>Validar utilizador</span></a></li>
				<li><a href='ver_utilizadores.php'><span>Visualizar utilizador</span></a></li>-->
				<li><a href='ver_utilizadores_todos.php'><span>Visualizar todos utilizadores</span></a></li>
				<li class='last'><a href='../logout.php'><span>Logout</span></a></li>
			</ul>
		</li>
		<li class='has-sub'><a href='#'><span>Inserir</span></a>
			<ul>
				<li><a href='inserirA.php'><span>Autores</span></a></li>
				<li><a href='inserirE.php'><span>Editoras</span></a></li>
				<li><a href='inserirL.php'><span>Livros</span></a></li>
				<li class='last'><a href='inserirU.php'><span>Utilizadores</span></a></li>
			</ul>
		</li>
		<li class='has-sub'><a href='#'><span>Atualizar</span></a>
			<ul>
				<li><a href='atualizarA.php'><span>Autores</span></a></li>
				<li><a href='atualizarE.php'><span>Editoras</span></a></li>
				<li><a href='atualizarL.php'><span>Livros</span></a></li>
				<li class='last'><a href='atualizarC.php'><span>Clientes</span></a></li>
			</ul>
		</li>
		<li class='has-sub'><a href='#'><span>Remover</span></a>
			<ul>
				<li class='last'><a href='removerV.php'><span>Vendas</span></a></li>
			</ul>
		</li>
		<!--<li class='has-sub'><a href='#'><span>Procurar</span></a>
			<ul>
				<li><a href='procurarA.php'><span>Autores</span></a></li>
				<li><a href='procurarE.php'><span>Editoras</span></a></li>
				<li><a href='procurarL.php'><span>Livros</span></a></li>
				<li class='last'><a href='procurarC.php'><span>Clientes</span></a></li>
			</ul>
		</li>-->
	</ul>
</nav>