<nav>
	<ul>
		<li class='active'><a href='pag_user.php'><span>Home</span></a></li>
		<li class='has-sub'><a href='#'><span>Acesso</span></a>
			<ul>
				<li class='last'><a href='../logout.php'><span>Logout</span></a></li>
			</ul>
		</li>
		<li class='has-sub'><a href='#'><span>Mostrar</span></a>
			<ul>
				<li><a href='mostrarA.php'><span>Autores</span></a></li>
				<li><a href='mostrarL.php'><span>Livros</span></a></li>
				<li class='last'><a href='mostrarC.php'><span>Compras</span></a></li>
			</ul>
		</li>
		<li class='has-sub'><a href='#'><span>Comprar</span></a>
			<ul>
				<li class='last'><a href='comprarL.php'><span>Livros</span></a></li>
			</ul>
		</li>
	</ul>
</nav>